### PR TITLE
Show command name used by helm ag

### PR DESCRIPTION
**Pull request by justbur**
To do this allow specification of a function in
spaceline--helm-buffer-ids.

### CODE REVIEW

**Comment by justbur** [comment]
Please change the wording if you don't like it

**Comment by justbur** [comment]
@TheBB maybe you don't like this?

**Comment by TheBB** [comment]
Sorry, I haven't had time to look at this over Christmas and new year.

**Comment by TheBB** [comment]
Merged, thanks!

**Pull request merged**
