### PR TITLE
Use total width instead of text width

### PR DESCRIPTION
**Pull request by galaunay**
### Problem
`spaceline--adjust-to-window` uses `window-width` to get the available horizontal space.
`window-width` is an alias for `window-body-width`, which return the width of the text area (and not the width of the window).
This can be a problem when the text is constrained to a width inferior to the window width (with [visual-fille-column mode](https://github.com/joostkremers/visual-fill-column) for example).
In this later case spaceline removes elements from the modeline while their is enough room for them.

### Solution
Use `window-total-width` instead of `window-width`.

### CODE REVIEW

**Comment by deb0ch** [comment]
I just tried your patch, and even though I like the idea of having Spaceline working better with visual-fill-column-mode, which it does with your patch (I installed it for testing), it also breaks the window width computation in normal cases.

Using `window-total-width` can put my spaceline 1 to 7 characters off on the rightmost window when I have a split, hiding the very last segment (and this also depending on where I drag the split limit), whether visual-fill-column-mode is on or off. And this even when I add the `'floor` argument to `window-total-width`.

A little bit like #163 , but worse.

At least it doesn't happen with `window-width` in normal cases, so I would prefer to cover the general case well and not degrade it to support edge cases.

If you feel like investigating more, I would be glad to merge a solution that supports both cases !

**Comment by galaunay** [comment]
You are right, I didn't saw that.

I think this is due to the fact that `window-total-width` also includes the scrollbar and window delimiter widths. I modified the PR so that the spaceline computed width is `window-width` (width of the text area) plus `window-margins` (width of the right and left margins).

Fringes width (`window-fringes`) should also be taken into account to compute the total available width, but they are not supposed to exceed some pixel, and I don't know if it worths the trouble...

I tested it with and without margins: it works fine on my configuration.

**Comment by galaunay** [comment]
Is this solution seem good for you ?

**Comment by TheBB** [comment]
This seems to be ok. I've merged this. Thank you!

**Pull request closed without merging**
