### PR TITLE
Add file status to version-control segment

### PR DESCRIPTION
**Pull request by justbur**
Not sure about the status codes, but I thought it would be nice to have a little more info about the repository. This is file-level status. The repo-level status seems like it could be slow.

### CODE REVIEW

**Comment by justbur** [comment]
It doesn't refresh correctly after a commit it seems. If you like the idea, I'll look into why.

**Comment by TheBB** [comment]
Yes, I like the idea. I noticed that the current one doesn't refresh either, after branch changes. It's annoying and I would love to fix it.

**Comment by TheBB** [comment]
```lisp
(defun bb/vc-update ()
  (vc-mode-line (buffer-file-name)))
(add-hook 'magit-refresh-file-buffer-hook 'bb/vc-update)
```

?

**Comment by justbur** [comment]
This seems like the right one
```elisp
(add-hook 'magit-after-revert-hook 'vc-refresh-state)
```

**Comment by TheBB** [comment]
I don't have that function....

**Comment by TheBB** [comment]
I will look at making a unicode version of this later, I think.

**Pull request merged**
