### PR TITLE
Use outline-minor-mode compatible headers

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by vyp** [comment]
Why doesn't outline support the previous type? Perhaps this could suggested to outline, if it hasn't already?

**Comment by tarsius** [comment]
Outline needs to be able to distinguish between comments and headings, so it treats comments that begin with `;; ` as actual comments and comments that begin with `;;; ` as headings. To nest sections you can use even more semicolons, but three are required for a top-level section.

**Comment by vyp** [comment]
Oh right yeah I remember that, that makes sense thanks. 👍

**Comment by tarsius** [comment]
Friendly ping for @TheBB!

**Comment by TheBB** [comment]
Thanks @tarsius, sorry for the wait.

**Comment by tarsius** [comment]
You are welcome! No problem.

**Pull request merged**
