### PR TITLE
Responsive spaceline

### PR DESCRIPTION
**Pull request by deb0ch**
I've always wanted the Spaceline to only display the most useful information, even in narrow split windows. Instead, the right-hand side kept being pushed out of the windows, so whenever you were splitting them you were missing some critical information, lost, wondering where you were in your buffer.

So I rolled up my sleeves and here it is: a responsive Spaceline 🎉 ✨ 

With this mechanism, the Spaceline gets adjusted to the width of the window by making the segments disappear and reappear by order of priority, and from the center to the sides in case of priority equality.

I've been working on it for some time now and I extensively debugged it as I went through every single step of the implementation, so as far as I've used it it's been pretty stable.

Although there is still some room for optimization, a particular effort was put into adopting a resource-friendly design, so the difference is not noticeable even on my Raspberry Pi 😸 

The way it woks is by storing the code of the segments into a global, buffer-local and target-specific list of segments data, along with some runtime-data:

``` elisp
'(((<segment-1-code>) . ((shown . t) (length . 0) (priority . 42)))
  ((<segment-2-code>) . ((shown . t) (length . 0) (priority . 42)))
  ...
  ((<segment-n-code>) . ((shown . t) (length . 0) (priority . 42))))
```
and pushing the same runtime data into a separate list:
``` elisp
'(((shown . t) (length . 0) (priority . 42))
  ((shown . t) (length . 0) (priority . 42))
  ...
  ((shown . t) (length . 0)) (priority . 42))
```
This way we can decide wether to show the segment or not by modifying the `shown` property in the second list and reading it in the first list to decide wether to execute that code or not.

The order of appearance / disappearance is decided by the order of the second list, while the order of the first one decides of their spatial organization.

More implementation details can be found in the docstrings of the macros and functions that I wrote to achieve this.

### CODE REVIEW

**Comment by TheBB** [comment]
Thanks for this! If it works as advertised it's really cool. I'm away until Monday however, so can't check for a few days.

**Comment by deb0ch** [comment]
Aaaaarh, I didn't have in mind that recompilation without reloading the buffer was a feature, hence the failed tests.

I should definitly start noticing the existence of these automated tests files *before* submitting in the future.

It's all fixed now :smile_cat:

Except for that, glad you like the idea :smile_cat: Looking forward to having your feedback.

**Comment by TheBB** [comment]
Sorry about the delay. I'm in the middle of moving. Planning to take a look at this over the weekend.

**Comment by deb0ch** [comment]
Hey, just pinging in. Have you had the time to start taking a look at it ?

**Comment by TheBB** [comment]
Hey,

Sorry about the wait. :-(

This looks excellent and it works well in my testing. I have one big concern and a few smaller ones, so let's do the big one first. 

In the previous (that is to say, current) version of Spaceline, the compiler generates code for all the segments, which is dumped into one big defun. This is to let Emacs' compiler do as much optimization as it possibly can. What you're doing now, however, is to `eval` code blocks at runtime. This potentially ruins some optimization, doesn't it? I'm surprised that you say it's not noticeable even on a pi, which if true is fine by me, but makes me a bit uneasy still. Do you have any benchmarks?

So just let me see if I got this straight:

The “target function”:
* initializes the dual data structures you describe, if not already done
* renders the modeline (basically, this is the same as calling the “old” target function): here, all segments are rendered without regard to priority or whatever, and the result is stored in a local variable
* then, if the modeline is too long, it shuts down however many segments it needs (from the “end”) to make it shorter (the runtime data structure is sorted by priority)
* conversely, if it's short, it tries to display hidden segments (in the other direction) to make it longer
* if any of these result in changes (the length changed), the “target function” is called again (this *should* recurse only once from what I can tell)
* `spaceline--format` now has the finished product, so return

In principle I don't mind merging this right now. I would eventually like to make some tweaks but if the performance really is good enough, I can do that later on in the master branch rather than before merging. I think I've kept you waiting quite long enough. :-)

Good work, and clever use of mutable lists. :+1:

**Comment by deb0ch** [comment]
Hey, glad you like it !

I confirm that you got it straight, everything was accurate :+1:

I haven't benchmarked it in a very scientific way, I just noted that I couldn't see a slowdown with my human perception on my own laptop, so I decided to compare before / after on my raspi and couldn't perceive a slowdown either

I don't doubt that there is some overhead though, just none that I can perceive.

I didn't know that the byte compiler did runtime optimization, until now I thought that it just made it faster to *load*, not to *run* 🤔 I wonder if there is a way to make the byte compiler optimize these chunks of code, like using a `#` or so.

Would you like me to run a benchmark of some sort, like using the profilier or so ? I'm not very sure how to operate to get accurate and repeatable results without external noise though.

**Comment by TheBB** [comment]
> I didn't know that the byte compiler did runtime optimization, until now I thought that it just made it faster to load, not to run

I don't know that it does either, but I prefer to leave it up to the byte compiler to do it if it can. :-P

I was actually working on some small changes: https://github.com/TheBB/spaceline/commits/responsive. The commit messages are placeholders, but basically what I achieved was:

* *guarantee* that the modeline function doesn't endlessly recurse
* evaluate the bindings for `default-sep` and `other-sep` at compile time
* use `cl-incf`, `cl-decf` and `pop` as utility functions/macros
* streamline the declaration and initialization of the runtime data structures a bit (create the whole alist at once, then copy it with `copy-tree`)

One question though: https://github.com/deb0ch/spaceline/blob/2ad2d0f60b11814850755a674fb1e42299fbde8f/spaceline.el#L523-L530

`spaceline--gen-separator` resets the `needs-separator` flag, so this won't ever run. Also, if it does run, I guess you need `(cdr last-visible-segment)` in the second let-binding since `last-visible` segment will be a cons cell where the car is a code block.

When I moved it above the call to `spaceline--gen-separator` and made that change, I saw that some hidden segments didn't show up again.

For the record, the branch I tried that on is my own, so it's possible that I messed something up there, of course.

**Comment by TheBB** [comment]
Don't worry about the benchmarks, I'll deal with it.

**Comment by TheBB** [comment]
Okay, I have a branch with some good optimizations now, ready to push. I'll use it for a bit myself first.

**Comment by deb0ch** [comment]
I was already feeling like I was doing some black magic, but I feel like you're doing even blacker magic here :smile_cat: 

Haven't understood yet exactly what you were doing where, will get to it shortly.

Which branch should I look at, `responsive` or `responsive-new` ?

One more thing, maybe the big big `some quality of life improvement` commit could be broken down into as many commits as there are entries in its commit message list ? This would make tracking down changes way easier. I would understand if you didn't have time for that though.

Well, all that said, glad to see all your optimization work ! :thumbsup::sparkles:

**Comment by TheBB** [comment]
Yeah I could do that. I'll look at it later today.

I merged `responsive-new` into `responsive`, the latter is the place to be.

**Comment by TheBB** [comment]
Okay, my branch now has better commits.

**Comment by TheBB** [comment]
Merged! Thank you for this, great work!

**Comment by deb0ch** [comment]
Yay ! I love that this is merged thank you ! :tada: :thumbsup: :sparkles:

**Pull request merged**
